name: Terraform Cloud CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.11.2
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Verify tfplan file exists
        run: |
          if [ -f tfplan ]; then echo "File exists"; else echo "File does not exist"; exit 1; fi

      - name: Upload Terraform Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan  # This refers to the tfplan file generated in the runner's environment

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production
    needs: terraform-plan

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve plan.out

  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest
    environment: production
    needs: terraform-apply

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Terratest
        run: |
          go test -v ./test/terraform_network_test.go
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: terratest-results
          path: terratest-results.xml
